version: 0.2

phases:
  install:
    commands:
        - echo "initializing"
  pre_build:
    commands: 
        - echo "Installing node_modules"
        - npm install
  build:
    commands:
        - echo "Creating build"
        - npm run build && aws s3 sync build/ s3://react-demo-build
  post_build:
    commands:
        - echo "Finishing up"